--  Configuration for light_tasking_pico generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Light_Tasking_Pico_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "light_tasking_pico";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := release;

   type Device_Kind is (rp2040, rp2350);
   Device : constant Device_Kind := rp2040;

end Light_Tasking_Pico_Config;
